---
- name: Reboot OS
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  listen: 'Reboot OS'

- name: SSHポート クローズ
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: stopped
  delegate_to: 127.0.0.1
  listen: 'Reboot OS'

- name: SSHポート オープン待機
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 60
  delegate_to: 127.0.0.1
  listen: 'Reboot OS'
